/** Prisma model names (PascalCase) that carry a direct `tenantId` column. */
export const TENANT_SCOPED_MODELS = new Set([
  'User',
  'Driver',
  'Vehicle',
  'Company',
  'Assignment',
  'TransportRequest',
  'CalendarEvent',
  'Request',
  'Document',
  'VehicleHandover',
  'Accident',
  'CompanyEmail',
  'Notification',
  'Reminder',
  'MorningCheckin',
  'ServiceRecord',
  'Conversation',
  'AuditLog',
  'DriverLocationHistory',
  'DriverLocationLatest',
  'CustomerAssignmentMessage',
  'UserInvitation',
  'WorkSession',
  'VehicleEquipment',
  'DriverLicense',
  'LicenseCheck',
  'ChecklistTemplate',
  'DepartureCheck',
  'Defect',
  'DefectStatusLog',
  'DepartureCheckReminderState',
  'Fine',
  'FineStatusLog',
  'FleetTrip',
  'FleetTripPurposeLog',
  'FleetDrivingEvent',
  'FleetFuelEntry',
  'FuelCardImportBatch',
  'FuelCardTransaction',
  'FleetMaintenanceRule',
  'Device',
  'VehicleTelemetryLatest',
  'VehicleDtc',
  'MessageAttachment',
  'MessageTranslation',
  'DddFile',
  'TachoProviderCredential',
  'TachoActivity',
  'TachoInfringement',
  'TachoDownloadSchedule',
  'TelemetryQuarantine',
  'EquipmentIssuance',
  'TenantBillingProfile',
  'RateCard',
  'RateCardItem',
  'Invoice',
  'InvoiceLine',
  'InvoiceAssignmentClaim',
  'InvoiceNumberSequence',
  'InvoicePayment',
  'InvoiceDeliveryAttempt',
  'InvoiceAuditEvent',
  'DunningNotice',
  'DatevExport',
  'Location',
  'Tour',
  'TourStop',
  'WorkTimeEvent',
]);

export function isTenantScopedModel(model: string): boolean {
  if (!model) {
    return false;
  }

  const normalizedModel = model[0].toUpperCase() + model.slice(1);
  return TENANT_SCOPED_MODELS.has(normalizedModel);
}
