/** Prisma model names (PascalCase) that carry a direct `tenantId` column. */
export const TENANT_SCOPED_MODELS = new Set([
  'User',
  'Driver',
  'Vehicle',
  'Company',
  'Assignment',
  'TransportRequest',
  'CalendarEvent',
  'Request',
  'Document',
  'VehicleHandover',
  'Accident',
  'CompanyEmail',
  'Notification',
  'Reminder',
  'MorningCheckin',
  'ServiceRecord',
  'Conversation',
  'AuditLog',
  'DriverLocationHistory',
  'DriverLocationLatest',
  'CustomerAssignmentMessage',
  'UserInvitation',
  'WorkSession',
  'VehicleEquipment',
  'DriverLicense',
  'LicenseCheck',
  'ChecklistTemplate',
  'DepartureCheck',
  'Defect',
  'DefectStatusLog',
  'DepartureCheckReminderState',
  'Fine',
  'FineStatusLog',
  'FleetTrip',
  'FleetDrivingEvent',
  'FleetFuelEntry',
  'FleetMaintenanceRule',
]);

export function isTenantScopedModel(model: string): boolean {
  return TENANT_SCOPED_MODELS.has(model);
}
