export type DriverNotifyKey =
  | 'request_approved'
  | 'request_rejected'
  | 'assignment_created'
  | 'checkin_added_to_einsatzplan'
  | 'messenger_message'
  | 'transport_approved'
  | 'transport_rejected'
  | 'license_check_due'
  | 'license_check_reminder'
  | 'license_check_approved'
  | 'license_check_rejected'
  | 'license_expiry_soon'
  | 'departure_check_reminder'
  | 'defect_confirm_due'
  | 'fine_assigned';
