/** Annex 1C card EF file identifiers (Gen1). */
export const EF_APPLICATION_IDENTIFICATION_GEN1 = 0x0501;
export const EF_EVENTS_DATA_GEN1 = 0x0502;
export const EF_FAULTS_DATA_GEN1 = 0x0503;
export const EF_DRIVER_ACTIVITY_DATA_GEN1 = 0x0504;
export const EF_VEHICLES_USED_GEN1 = 0x0505;
export const EF_IDENTIFICATION_GEN1 = 0x0520;

/** Gen2 FIDs map to the same decoders. */
export const EF_APPLICATION_IDENTIFICATION_GEN2 = 0x0521;
export const EF_EVENTS_DATA_GEN2 = 0x0522;
export const EF_FAULTS_DATA_GEN2 = 0x0523;
export const EF_DRIVER_ACTIVITY_DATA_GEN2 = 0x0524;
export const EF_VEHICLES_USED_GEN2 = 0x0525;
export const EF_IDENTIFICATION_GEN2 = 0x0526;

export const CARD_RECORD_DATA = 0x00;
export const CARD_RECORD_SIGNATURE = 0x01;

export const KNOWN_CARD_FIDS = new Set([
  EF_APPLICATION_IDENTIFICATION_GEN1,
  EF_EVENTS_DATA_GEN1,
  EF_FAULTS_DATA_GEN1,
  EF_DRIVER_ACTIVITY_DATA_GEN1,
  EF_VEHICLES_USED_GEN1,
  EF_IDENTIFICATION_GEN1,
  EF_APPLICATION_IDENTIFICATION_GEN2,
  EF_EVENTS_DATA_GEN2,
  EF_FAULTS_DATA_GEN2,
  EF_DRIVER_ACTIVITY_DATA_GEN2,
  EF_VEHICLES_USED_GEN2,
  EF_IDENTIFICATION_GEN2,
]);

export const GEN1_CARD_FIDS = new Set([
  EF_APPLICATION_IDENTIFICATION_GEN1,
  EF_EVENTS_DATA_GEN1,
  EF_FAULTS_DATA_GEN1,
  EF_DRIVER_ACTIVITY_DATA_GEN1,
  EF_VEHICLES_USED_GEN1,
  EF_IDENTIFICATION_GEN1,
]);

export const GEN2_CARD_FIDS = new Set([
  EF_APPLICATION_IDENTIFICATION_GEN2,
  EF_EVENTS_DATA_GEN2,
  EF_FAULTS_DATA_GEN2,
  EF_DRIVER_ACTIVITY_DATA_GEN2,
  EF_VEHICLES_USED_GEN2,
  EF_IDENTIFICATION_GEN2,
]);

/** VU TREP transfer block tag (Annex 1C). */
export const TREP_BLOCK_TAG = 0x76;

export const VU_BLOCK_OVERVIEW_GEN1 = 0x01;
export const VU_BLOCK_ACTIVITIES_GEN1 = 0x02;
export const VU_BLOCK_EVENTS_FAULTS_GEN1 = 0x03;
export const VU_BLOCK_DETAILED_SPEED_GEN1 = 0x04;
export const VU_BLOCK_TECHNICAL_DATA_GEN1 = 0x05;

export const VU_BLOCK_OVERVIEW_GEN2 = 0x21;
export const VU_BLOCK_ACTIVITIES_GEN2 = 0x22;
export const VU_BLOCK_EVENTS_FAULTS_GEN2 = 0x23;
export const VU_BLOCK_DETAILED_SPEED_GEN2 = 0x24;
export const VU_BLOCK_TECHNICAL_DATA_GEN2 = 0x25;

export const VU_EVENT_DRIVING_WITHOUT_CARD = 0x05;

/** ActivityChangeInfo bit masks (2-byte big-endian field). */
export const SLOT_MASK = 0x8000;
export const CREW_MASK = 0x4000;
export const CARD_INSERTED_MASK = 0x2000;
export const ACTIVITY_MASK = 0x1800;
export const MINUTES_MASK = 0x07ff;
export const ACTIVITY_SHIFT = 11;

export const ACTIVITY_REST = 0;
export const ACTIVITY_AVAILABLE = 1;
export const ACTIVITY_WORK = 2;
export const ACTIVITY_DRIVING = 3;

export const MINUTES_PER_DAY = 1440;

export const DRIVER_CARD_TYPE_ID = 0x01;
